name: AI CI Pipeline

on:
  push:
    branches: ["feature/**"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  ai-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install ".[all]" || true
            pip install pytest flake8 httpx fastapi uvicorn || true
          fi

      # --- Lint ---
      - name: Lint (Flake8)
        run: flake8 . --count --max-complexity=12 --max-line-length=120 --statistics

      # --- Unit Test ---
      - name: Unit Test (pytest -m unit)
        run: pytest -q -m "unit" || echo "No unit tests"

      # --- Integration Test (PR to dev/main) ---
      - name: Integration Test (pytest -m integration)
        if: github.event_name == 'pull_request' && (github.base_ref == 'dev' || github.base_ref == 'main')
        run: pytest -q -m "integration" || echo "No integration tests"
